affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: 3
grid_eps: 0.02
grid_range:
- -1
- 1
k: 3
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 0
symbolic.funs_name.0:
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
symbolic.funs_name.1:
- - '0'
- - '0'
- - '0'
- - '0'
- - '0'
symbolic.funs_name.2:
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
symbolic.funs_name.3:
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
symbolic.funs_name.4:
- - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
symbolic.funs_name.5:
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
symbolic.funs_name.6:
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
symbolic.funs_name.7:
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
symbolic.funs_name.8:
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
symbolic.funs_name.9:
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
symbolic_enabled: true
width:
- - 6
  - 0
- - 1
  - 0
- - 5
  - 0
- - 8
  - 0
- - 4
  - 0
- - 9
  - 0
- - 6
  - 0
- - 7
  - 0
- - 6
  - 0
- - 10
  - 0
- - 1
  - 0
