affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: 6
grid_eps: 0.02
grid_range:
- -1
- 1
k: 4
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 1
symbolic.funs_name.0:
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
symbolic.funs_name.1:
- - '0'
  - '0'
  - '0'
  - '0'
symbolic_enabled: false
width:
- - 6
  - 0
- - 4
  - 0
- - 1
  - 0
